apiVersion: v1
kind: Secret
metadata:
 name: elastalert-config-secret
type: Opaque
stringData:
  elastalert_config: |-
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: true
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: elasticsearch-master
    es_port: 9200
    writeback_index: elastalert
    use_ssl: true
    verify_certs: true
    ca_certs: /certs/ca.crt
    alert_time_limit:
      minutes: 2880
    alert:
    - "email"
    # Email alert settings
    smtp_host: smtp.gmail.com
    smtp_port: 587
    smtp_ssl: false
    from_addr: fuyosuruclone@gmail.com
    email:
      - fuyosuruclone@gmail.com
    smtp_auth_file: /opt/elastalert/config/smtp_auth.yaml