apiVersion: v1
kind: Secret
metadata:
 name: elastalert-rules-secret
type: Opaque
stringData:
  gmail: |-
    type: frequency
    index: test-email-*
    num_events: 1
    timeframe:
      minutes: 5
    filter:
    - query:
        query_string:
          query: "error"
    alert:
    - "email"
    email:
    - fuyosuruclone@gmail.com