apiVersion: v1
kind: Secret
metadata:
 name: elastalert-rules-secret
type: Opaque
stringData:
  ddos: |-
    name: "DDoS Attack Detection"
    type: metric_aggregation
    index: beats-*
    metric_agg_key: "message.keyword"
    metric_agg_type: value_count
    bucket_interval:
      minutes: 1
    query_key: "message.keyword"
    min_threshold: 400
    alert:
      - "email"
    email:
      - "fuyosuruclone@example.com" 
    realert:
      minutes: 1
    timestamp_field: "@timestamp"